---
 
- hosts: alex@13.70.42.254  
  become: true
  tasks:
  
    - name: Install system updates for centos systems
      apt:
        update_cache=yes force_apt_get=yes cache_valid_time=3600
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"
  
