---
 
- hosts: alex@13.70.42.254  
  become: true
  pre_tasks:
  
  - name: update repository index (CentOS)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"
