---
- hosts: alex@13.70.42.254
  become: yes
  tasks:
  
  - name: Install the EPEL repo rpm
    dnf:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
      
  - name: Import the MSFT gpg key
    rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: Add the MsSQL server repo
    yum_repository:
      name: mssql
      description: Microsoft SQL repo
      file: /etc/yum.repos.d/msprod
      baseurl: https://packages.microsoft.com/rhel/7/mssql-server/
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      gpgcheck: yes


