---
- hosts: alex@13.70.42.254
  become: yes
  tasks:
  - name: Install the EPEL repo rpm
    dnf:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present


