---
 
- hosts: alex@13.70.42.254  
  become: true
  tasks:
  
    - name: Install httpd package
      apt:
        name: httpd
        state: present
        update_cache: True
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"
  
