---
 
- hosts: alex@13.70.42.254  
  become: true
  tasks:
  
  - name: Install system updates for centos systems
      yum:
        name: '*'
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"
